[package]
name = "clockify-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
serde_json = "1.0"
toml = "0.7"


[dev-dependencies]
anyhow = "1.0"
